# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            rimbamorani
tagline:          'a lifelong learner'
description:      'Lifelong Learner | Software Engineer & Data Analyst'
url:              https://rimbamorani.dev
baseurl:          /

author:
  name:           'Aya Aurora Rimbamorani'
  url:            https://github.com/ayaar25

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/ayaar25/ayaar25.github.io

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
